services:
  db:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_PORT: ${PGPORT}
    ports:
      - "5432:${PGPORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles:
      - db

  tiger-agent:
    image: ghcr.io/timescale/tiger-agent:latest
    env_file:
      - .env
    environment:
      SLACK_APP_TOKEN: ${SLACK_AGENT_APP_TOKEN}
      SLACK_BOT_TOKEN: ${SLACK_AGENT_BOT_TOKEN}
      SERVICE_NAME: ${SERVICE_NAME:-tiger-eon}
    volumes:
      - ./mcp_config.json:/app/mcp_config.json:ro
      - ./prompts:/app/prompts:ro
    ports:
      - "5678:5678"
    command:
      [
        "uv",
        "run",
        "tiger_agent",
        "run",
        "--mcp-config",
        "/app/mcp_config.json",
      ]

  tiger-slack-ingest:
    image: ghcr.io/timescale/tiger-slack-ingest:latest
    env_file:
      - .env
    environment:
      SLACK_APP_TOKEN: ${SLACK_INGEST_APP_TOKEN}
      SLACK_BOT_TOKEN: ${SLACK_INGEST_BOT_TOKEN}

  tiger-slack-mcp-server:
    image: ghcr.io/timescale/tiger-slack-mcp:latest
    env_file:
      - .env
    environment:
      PORT: 80
    ports:
      - "3001:80"

  tiger-gh-mcp-server:
    image: ghcr.io/timescale/tiger-github-mcp:latest
    env_file:
      - .env
    environment:
      PORT: 80
    ports:
      - "3002:80"
    profiles:
      - github

  tiger-linear-mcp-server:
    image: ghcr.io/timescale/tiger-linear-mcp:latest
    env_file:
      - .env
    environment:
      PORT: 80
    ports:
      - "3003:80"
    profiles:
      - linear
volumes:
  postgres_data:
