#!/bin/bash

downloadDir=$(pwd)/download

# get bun
bunCmd=$(which bun 2>/dev/null || echo "$downloadDir/bun")
if [ ! -f "$bunCmd" ]; then
    echo Downloading bun to "$bunCmd"
    curl -L -o "$bunCmd" https://bun.com/install
    chmod +x "$bunCmd"
    
    # install
    $bunCmd
fi

# Run the setup
exec bun setup